### ISSUE TITLE
3D point cloud visualization error

### ISSUE THREAD

**Issue by chytsa** [vevenom/RoomLayout3D_RandC#1]
Excuse me, I wonder why do I produce wrong point cloud projection during visualization?
Is it cause by the dependence packages?
Or the process computing the depth and camera parameters for projecting point cloud? 

![Screenshot from 2020-09-01 22-46-14](https://user-images.githubusercontent.com/25762327/91866433-19830f80-eca5-11ea-8363-3b5ea5624f4e.png)

**Comment by vevenom** [comment]
Hi,

I am not sure that I can see the issue here. Actually, the 3D layout looks good, right? Your visualization seems to be correct and consistent with my outputs and with the underlying scene. 

You can change `get_layout_pc` to show layout textured with color image with a single line change in the function:

`layout_image = self.visualize_2d_layout_helper(overlay_color=True)`

![image](https://user-images.githubusercontent.com/9026494/91868220-cabd8180-ec74-11ea-91bb-f5d48d9b68ed.png)

This might help you to interpret the results.

**Comment by chytsa** [comment]
Yes, now it works as I want.
It turns out to be the parameters difference. lol
Thank you very much.
