### ISSUE TITLE
a problem on  metric

### ISSUE THREAD

**Issue by CYang0515** [vevenom/RoomLayout3D_RandC#2]
I use planercnn and mseg network to produce the inputs on scannet_layout dataset. There are about 15 examples to fail. And we only calculate the metric on successful cases using [(https://github.com/vevenom/ScanNet-Layout)]. The result is  
[2D IoU: 0.645  PE:0.157 EE:25.364 RMSE: 0.455], there is a gap on EE metric, is there any question? Please.

**Comment by vevenom** [comment]
Hi,

I need more information to answer your concern. 

if I understand correctly, you ran our approach on Scannet-Layout and evaluated only on successful cases. What do you consider as a successful case?  If you are evaluating only on examples where the method retrieves good layouts, than the numbers should be much higher, so I am slightly confused. Also, are you using sensor depth as input, or are you predicting the depth using CNNs?

As noted in the repo, this reimplementation slightly varies from the original one that was used in the paper which might have led to different results (might be the combination of hyperparameters for example?). Not by such large margin though.

**Comment by CYang0515** [comment]
The procedure raises "Infeasible" or the running time is more than 2 minutes, we regard it to fail. And we use the predicted depth by planercnn. And we find there are some hyperparameters that are different from paper, I adjust some hyperparameter  to get closer results to paper.

**Comment by vevenom** [comment]
I see. Yes that is an interesting point, when the "Infeasible" event occurs in the code, it implies that the method detected that the given combination of candidate components is wrong, indeed. 

If you are relying on predicted depth, than these results do not seem to be much different from the results in the paper. 

There are few differences that you should consider to improve the results further. This reimplementation is actually intended to run with depth from sensor as input so you can try the following. Use the predicted plane parameters from PlaneRCNN instead of performing plane fitting. I believe that PlaneRCNN doesn't output the normalized plane parameters, and there is some detail on how to get the plane offset in their repository. In the experiments we found that this is the better option when the g.t. depth is not available.

**Comment by CYang0515** [comment]
I have used the predicted parameter by PlaneRCNN. I want to confirm if the fail case don't contribute to the final metric?

**Comment by vevenom** [comment]
Actually, these examples do contribute to the final metric in the paper. Even though the PULP solver suggests that the solution is infeasible, it will still output solution that minimizes the cost function. We simply used this solution as the output in the original version but as the algorithm detects that this solution is actually bad, that is changed in this implementation.

**Comment by vevenom** [comment]
Closing the Issue. Please feel free to reopen or email directly if there are any further questions.
