### ISSUE TITLE
Visualization question

### ISSUE THREAD

**Issue by marcomiglionico94** [vevenom/RoomLayout3D_RandC#6]
Hello, I have a question regarding the visualization. Let's say that I want to visualize only the 3D room layout(without point clouds of the objects) just by using the planes in the npy file and the depth map. Without running the optimization and using the segmentation. Is that possible using Open3D?

**Comment by vevenom** [comment]
if you want to visualize the results without scene clutter, just remove `pcd_clutter` from this line of code:

https://github.com/vevenom/RoomLayout3D_RandC/blob/2ec3d8b0be10a7941349248690e3563c345e17ae/RoomLayoutEstimator.py#L1568

If you want to visualize the initial planes only, you might want to adapt `generate_depth_map_from_solution` to use the initial planes instead of layout components:

https://github.com/vevenom/RoomLayout3D_RandC/blob/2ec3d8b0be10a7941349248690e3563c345e17ae/RoomLayoutEstimator.py#L1116
